name: Unlock Capsules

on:
  schedule:
    - cron: "*/1 * * * *" # every minute
  workflow_dispatch:

jobs:
  unlock:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run backfill script
        run: npx ts-node scripts/backfillPublicWall.ts
